[project]
name = "kokovoice"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "kokoro-onnx>=0.4.9",
    "soundfile>=0.13.1",
    "streamlit>=1.28.0",
]
